version: "3.9"

services:
  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: "rabbitmq_container"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ./docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_network
networks:
  rabbitmq_network:
    driver: bridge
